---
title: "Trabajo 1 TAE - Salud"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Librerías

```{r}
library(tidyverse)
library(data.table)
library(readxl)
```

# Algunas funciones necesarias

## Función para la moda

```{r}
# Función para la moda
getmode <- function(v, na.rm = TRUE) {
  if(na.rm == TRUE) {
    v <- v[!is.na(v)]
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
   } else {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
  }
}
```


# Lectura de datos

```{r}
raw_encuesta <- fread("databases/calidad_vida_ok.csv", encoding = "UTF-8") %>% 
  as_tibble()
```

# Creación de la base de datos

```{r}
db_escolaridad <- raw_encuesta %>% 
  group_by(encuesta_calidad.barrio) %>% 
  summarize(n = n(),
            proporcion_lectoescritura = sum(`encuesta_calidad.p_35` == 1, na.rm = TRUE) / sum(!is.na(`encuesta_calidad.p_35`), na.rm = TRUE),
            proporcion_escolaridad_actual = sum(`encuesta_calidad.p_36` == 1, na.rm = TRUE) / sum(!is.na(`encuesta_calidad.p_36`), na.rm = TRUE),
            estudio_ultimo_ano = sum(`encuesta_calidad.p_37` == 1, na.rm = TRUE) / sum(!is.na(`encuesta_calidad.p_37`), na.rm = TRUE),
            ultimo_nivel_estudio = getmode(`encuesta_calidad.p_45`, na.rm = TRUE),
            tipo_institucion_educativa = getmode(`encuesta_calidad.p_49`, na.rm = TRUE)
          )
```

# Establecimiento de tipos de datos

```{r}
db_escolaridad <- db_escolaridad %>% mutate(
  ultimo_nivel_estudio = as.factor(ultimo_nivel_estudio),
  tipo_institucion_educativa = as.factor(tipo_institucion_educativa)
)
```

# Escritura de los datos

```{r}
write_excel_csv2(db_escolaridad, "databases/db_escolaridad.csv")
```

# Analisis preliminar de los datos

## Medias y cuartiles

```{r}
summary(db_escolaridad)
```

## Desviaciones estandar

```{r}

```


# Graficas

```{r}
library(GGally)
ggpairs(db_escolaridad[, 3:7], aes(alpha = 0.4))
```

Mapa de calor
