---
output: html_document
---
* <span style="color:#FF0000">**Grupo 1: Alto uso de recursos, mayor discapacidad - 27 barrios**</span>

Es un grupo con alto uso de recursos dado que son los que más consultas y urgencias presentan, además de la más alta discapacidad (10.4%). En general, este grupo percibió que tiene un acceso a salud menor que los demás. Es un grupo que geográficamente se encuentra en la periferia del Valle de Aburrá y en algunos barrios del centro de la ciudad.

  + Mayor número de consultas 3.5932 (1.5984)
  + Mayor proporción de calidad de consulta buena 0.8653 (0.1567)
  + Grupo con mayor proporción de discapacidad, 0.1039 (0.0989)
  + Menor acceso a salud 2.7959 (0.2405)
  + Mayor percepción de la calidad de la salud mala 0.1141 (0.127)
  + Mayor negación de la atención por tramitología excesiva 0.1111 (0.3203)
  + Mayor uso de programas de prevención 2.3148 (2.4696)
  + Mayor número de asistencias a urgencias 2.341 (1.9364)
  + Mayor percepción de la calidad de urgencias buena 0.6575 (0.382)
